name: Test package on pull request
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - 'develop'
      - 'master'
jobs:
  pr-test:
    name: Test package with Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        swift: ["6"]
    steps:
      - name: Setup Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift }}
          skip-signature-verification: true
      - name: Swift-version
        run: swift --version
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build
        run: swift build
      - name: Test
        run: swift test --enable-code-coverage
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
